### ISSUE TITLE
After updating to the newest version: No such file or directory

### ISSUE THREAD

**Issue by dm0nkey** [tetreum/ocomposer#2]
I used this tool for some days and updated it to the newest version, after doing so I recive following error on running it with any parameter

error: No such file or directory

**Comment by tetreum** [comment]
:s Post the output for: `ls -l /usr/bin/ocomposer`
(if there are no results, install ocomposer again, remember to be sudoer)
¿How did you update it?

**Comment by dm0nkey** [comment]
`-rwxr-xr-x 1 root root 27373 Mai 21 14:28 /usr/bin/ocomposer`

reinstalled it already, same isue

updated it via: 

> curl -s https://raw.githubusercontent.com/tetreum/ocomposer/master/compiled/installer | bash

all requirements are up to date

**Comment by tetreum** [comment]
WTF..... If you manually replace /usr/bin/ocomposer with this:
https://raw.githubusercontent.com/tetreum/ocomposer/master/compiled/ocomposer
It will work. If you do the same by wget, it will show your error :S

I wil keep looking at this, meanwhile, replace the file manually. I'm sorry for this inconvenience.

**Comment by tetreum** [comment]
Fixed, stupid windows and his invisible format conversions.

You can do:
`curl -s https://raw.githubusercontent.com/tetreum/ocomposer/master/compiled/installer | bash`

And it should work.

**Comment by dm0nkey** [comment]
yeah, I replaced it manually before, just want to let you know the script isn't working right if it was installed already in the past

**Comment by tetreum** [comment]
Wasn't because it was already installed. The problem was that i compiled the latest version in Windows, so newline characters needed to be converted to Unix format.  Now it's working fine :p

**Comment by dm0nkey** [comment]
yeah, working now, tested it localy
