### ISSUE TITLE
Issue on install of add-on

### ISSUE THREAD

**Issue by Darkhole218** [tetreum/ocomposer#4]
ocomposer install death-notes.819
This occurs on any attempt to install any mod
`PHP` Fatal error:  Uncaught Error: Call to undefined function curl_init() in /usr/bin/ocomposer:559
Stack trace:
#0 /usr/bin/ocomposer(547): Oxide->curl('http://oxidemod...', Array, false)
#1 /usr/bin/ocomposer(528): Oxide->query('login/login', Array)
#2 /usr/bin/ocomposer(766): Oxide->login('*******', '*****')
#3 /usr/bin/ocomposer(786): OxideComposer->initOxide()
#4 /usr/bin/ocomposer(218): OxideComposer->install('death-notes.819')
#5 /usr/bin/ocomposer(126): CommandLine::install('death-notes.819')
#6 /usr/bin/ocomposer(933): CommandLine::init(Array)
#7 {main}
  thrown in /usr/bin/ocomposer on line 559`

**Comment by tetreum** [comment]
Please, check requirements section before executing it, you need curl:
https://github.com/tetreum/ocomposer#requirements

**Comment by Darkhole218** [comment]
Curl is installed.

**Comment by tetreum** [comment]
Nope, curl_init is part of php5-curl extension. http://php.net/manual/en/function.curl-init.php

**Comment by Darkhole218** [comment]
Ahh i must have a different version of curl installed. What would the package name be?

**Comment by tetreum** [comment]
Has that exact name, php5-curl. That's the php extension that uses libcurl which you may already have installed in your system.

**Comment by Darkhole218** [comment]
Unable to locate package.
